FPS = 60
SOLUTIONDELAY = 250

OUTSIDEDECORATIONPERCENTAGE = 5

BRIGHTBLUE = (0, 170, 255)
WHITE = (255, 255, 255)
BGCOLOR = BRIGHTBLUE
TEXTCOLOR = WHITE

SOUNDENABLED = False
SOUNDVOLUME = 0.2

UP = 'up'
DOWN = 'down'
LEFT = 'left'
RIGHT = 'right'

MAPWIDTH = 24
MAPHEIGHT = 20

CONTROLWIDTH = 48
CONTROLHEIGHT = 48

SOUNDDIRECTORY = 'Standard'

LEVELDIRECTORY = 'Original'
# LEVELDIRECTORY = 'Microban I'
# LEVELDIRECTORY = 'Microban II'
# LEVELDIRECTORY = 'Microban III'
# LEVELDIRECTORY = 'Sasquatch I'
# LEVELDIRECTORY = 'Sasquatch II'
# LEVELDIRECTORY = 'Sasquatch III'
# LEVELDIRECTORY = 'Sasquatch IV'
# LEVELDIRECTORY = 'Sasquatch V'
# LEVELDIRECTORY = 'Sasquatch VI'
# LEVELDIRECTORY = 'Sasquatch VII'
# LEVELDIRECTORY = 'Sasquatch VIII'
# LEVELDIRECTORY = 'Small Chessboards'
# LEVELDIRECTORY = 'Magic Sokoban'

IMAGEDIRECTORY = 'starpusher'
ZOOMFACTOR = 0.75
TILEWIDTH = int(50 * ZOOMFACTOR)
TILEHEIGHT = int(85 * ZOOMFACTOR)
TILEANGLEHEIGHT = int(40 * ZOOMFACTOR)

# IMAGEDIRECTORY = 'simple'
# ZOOMFACTOR = 1
# TILEWIDTH = int(48 * ZOOMFACTOR)
# TILEHEIGHT = int(48 * ZOOMFACTOR)
# TILEANGLEHEIGHT = int(48 * ZOOMFACTOR)

# IMAGEDIRECTORY = 'kenney'
# ZOOMFACTOR = 0.6
# TILEWIDTH = int(64 * ZOOMFACTOR)
# TILEHEIGHT = int(64 * ZOOMFACTOR)
# TILEANGLEHEIGHT = int(64 * ZOOMFACTOR)
